name: Deploy Python

on:
  workflow_dispatch:
  push: 
    tags: "v*"

jobs:
  python-checks:
    uses: ./.github/workflows/python.yml

  build:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build SDist
      run: pipx run build
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: dist/*.tar.gz

  publish:
    environment: pypi
    needs: [python-checks, build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: build
        path: dist
        merge-multiple: true
    # - name: Install tooling
    #   run: python -m pip install twine keyring artifacts-keyring
    # - name: Upload to ADO
    #   env: 
    #     TWINE_REPOSITORY_URL: https://pkgs.dev.azure.com/MusicalNinjas/FizzBuzz/_packaging/FizzBuzz/pypi/upload/
    #     TWINE_USERNAME: FizzBuzz
    #     TWINE_PASSWORD: ${{ secrets.ADO_TOKEN }}
    #   run: twine upload --non-interactive dist/*